// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGzlVFARYHo0mIsu0Njo-lGrvDdNnOaE',
    appId: '1:7797512915:web:044e3dd04a5aa5e0b35226',
    messagingSenderId: '7797512915',
    projectId: 'marn-48249',
    authDomain: 'marn-48249.firebaseapp.com',
    storageBucket: 'marn-48249.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47W8rOSWdLYiXQlVJNnA7VqIdrhTXEiU',
    appId: '1:7797512915:android:f40590ae07f493b1b35226',
    messagingSenderId: '7797512915',
    projectId: 'marn-48249',
    storageBucket: 'marn-48249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0mmaKO5hmSpHUQt8mvPgBrWogA0GClo',
    appId: '1:7797512915:ios:25cdaa59fbb1b1e1b35226',
    messagingSenderId: '7797512915',
    projectId: 'marn-48249',
    storageBucket: 'marn-48249.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM0mmaKO5hmSpHUQt8mvPgBrWogA0GClo',
    appId: '1:7797512915:ios:25cdaa59fbb1b1e1b35226',
    messagingSenderId: '7797512915',
    projectId: 'marn-48249',
    storageBucket: 'marn-48249.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbGzlVFARYHo0mIsu0Njo-lGrvDdNnOaE',
    appId: '1:7797512915:web:d9392c2e18afd6a1b35226',
    messagingSenderId: '7797512915',
    projectId: 'marn-48249',
    authDomain: 'marn-48249.firebaseapp.com',
    storageBucket: 'marn-48249.firebasestorage.app',
  );
}
