const fs = require('fs');

const enPath = 'src/locales/en/pages.json';
const arPath = 'src/locales/ar/pages.json';

const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const arData = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const enTermsSections = {
  s1: { title: "1. Acceptance of Terms", content: "By accessing and using MARN's services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform. We reserve the right to modify these terms at any time, and your continued use of the service constitutes acceptance of those changes." },
  s2: { title: "2. User Accounts", content: "You must create an account to access certain features of our platform. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years old to create an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete." },
  s3: { title: "3. Property Listings", content: "Property owners must ensure that all listing information is accurate, complete, and up-to-date. You must have legal authority to list and rent the property. Photos and descriptions must accurately represent the property. You are responsible for setting pricing, availability, and rental terms. MARN reserves the right to remove listings that violate our policies or applicable laws." },
  s4: { title: "4. Tenant Responsibilities", content: "Tenants agree to provide truthful information in rental applications. You are responsible for paying rent on time as agreed with the property owner. You must maintain the property in good condition and report any damages or maintenance issues promptly. You agree to comply with all lease terms and local laws and regulations." },
  s5: { title: "5. Payments and Fees", content: "All payments are processed securely through our platform. Property owners agree to pay applicable listing fees and service charges. Tenants may be required to pay application fees, security deposits, and rent through the platform. All fees are non-refundable except as explicitly stated in our refund policy. MARN is not responsible for any disputes regarding payments between property owners and tenants." },
  s6: { title: "6. Cancellation and Refunds", content: "Cancellation policies are set by individual property owners and must be clearly stated in the listing. Tenants should review cancellation policies before booking. Refunds, if applicable, will be processed according to the property's specific policy. MARN reserves the right to cancel bookings in cases of fraud, violation of terms, or safety concerns." },
  s7: { title: "7. Prohibited Conduct", content: "Users must not engage in fraudulent activities, provide false information, or misrepresent themselves. Harassment, discrimination, or abusive behavior toward other users is strictly prohibited. You may not use the platform for any illegal purposes or to violate any laws. Attempting to circumvent platform fees or conduct transactions outside the platform is forbidden. Posting misleading listings, spam, or unauthorized commercial content is not allowed." },
  s8: { title: "8. Verification and Background Checks", content: "MARN may conduct identity verification and background checks on users. By using our services, you authorize us to obtain such information. While we strive to verify users, MARN does not guarantee the accuracy or completeness of verification information and is not responsible for any issues arising from user interactions." },
  s9: { title: "9. Intellectual Property", content: "All content on the MARN platform, including logos, text, graphics, and software, is the property of MARN or its licensors. You may not copy, reproduce, distribute, or create derivative works from our content without explicit written permission. User-generated content (listings, reviews, photos) remains the property of the user but grants MARN a license to use such content for platform operations." },
  s10: { title: "10. Limitation of Liability", content: "MARN acts as a platform connecting property owners and tenants and is not a party to rental agreements. We are not responsible for the accuracy of listings, the conduct of users, or the condition of properties. MARN is not liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the platform. Our total liability shall not exceed the amount paid by you to MARN in the twelve months preceding the claim." },
  s11: { title: "11. Indemnification", content: "You agree to indemnify and hold harmless MARN, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses arising out of your use of the platform, violation of these terms, or infringement of any third-party rights." },
  s12: { title: "12. Dispute Resolution", content: "Any disputes arising from these terms or use of the platform shall be resolved through binding arbitration in accordance with the rules of the Cairo Regional Centre for International Commercial Arbitration (CRCICA). The arbitration shall take place in Cairo, Egypt. You waive your right to participate in class action lawsuits or class-wide arbitration." },
  s13: { title: "13. Governing Law", content: "These Terms of Service are governed by the laws of the Arab Republic of Egypt, without regard to its conflict of law provisions. Any legal action or proceeding shall be brought exclusively in the courts located in Cairo, Egypt." },
  s14: { title: "14. Contact Information", content: "If you have questions about these Terms of Service, please contact us at: Email: legal@marn.com, Phone: 01012345678, Address: Besides new Damietta University, New Damietta, Egypt" }
};

const arTermsSections = {
  s1: { title: "١. قبول الشروط", content: "من خلال الوصول إلى خدمات مارن واستخدامها، فإنك تقر بأنك قد قرأت وفهمت ووافقت على الالتزام بشروط الخدمة هذه. إذا كنت لا توافق على هذه الشروط، يرجى عدم استخدام منصتنا. نحتفظ بالحق في تعديل هذه الشروط في أي وقت، واستمرارك في استخدام الخدمة يمثل قبولاً لتلك التغييرات." },
  s2: { title: "٢. حسابات المستخدمين", content: "يجب عليك إنشاء حساب للوصول إلى ميزات معينة في منصتنا. أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك وعن جميع الأنشطة التي تحدث تحت حسابك. يجب أن يكون عمرك 18 عامًا على الأقل لإنشاء حساب. توافق على تقديم معلومات دقيقة وحديثة وكاملة أثناء التسجيل وتحديث هذه المعلومات لإبقائها دقيقة وحديثة وكاملة." },
  s3: { title: "٣. القوائم العقارية", content: "يجب على أصحاب العقارات التأكد من أن جميع معلومات القوائم دقيقة وكاملة وحديثة. يجب أن تكون لديك الصلاحية القانونية لعرض وتأجير العقار. يجب أن تمثل الصور والأوصاف العقار بدقة. أنت مسؤول عن تحديد الأسعار والتوافر وشروط الإيجار. تحتفظ مارن بالحق في إزالة القوائم التي تنتهك سياساتنا أو القوانين المعمول بها." },
  s4: { title: "٤. مسؤوليات المستأجرين", content: "يوافق المستأجرون على تقديم معلومات صادقة في طلبات الإيجار. أنت مسؤول عن دفع الإيجار في الوقت المحدد كما تم الاتفاق عليه مع مالك العقار. يجب عليك الحفاظ على العقار في حالة جيدة والإبلاغ عن أي أضرار أو مشاكل صيانة على الفور. توافق على الامتثال لجميع شروط عقد الإيجار والقوانين واللوائح المحلية." },
  s5: { title: "٥. المدفوعات والرسوم", content: "تتم معالجة جميع المدفوعات بأمان عبر منصتنا. يوافق أصحاب العقارات على دفع رسوم الإدراج ورسوم الخدمة المعمول بها. قد يُطلب من المستأجرين دفع رسوم الطلب، التأمين، والإيجار عبر المنصة. جميع الرسوم غير قابلة للاسترداد إلا كما هو منصوص عليه صراحة في سياسة الاسترداد الخاصة بنا. مارن ليست مسؤولة عن أي نزاعات تتعلق بالمدفوعات بين أصحاب العقارات والمستأجرين." },
  s6: { title: "٦. الإلغاء والاسترداد", content: "تُحدد سياسات الإلغاء من قبل أصحاب العقارات الفرديين ويجب توضيحها بوضوح في القائمة. يجب على المستأجرين مراجعة سياسات الإلغاء قبل الحجز. ستتم معالجة المبالغ المستردة، إن وجدت، وفقًا للسياسة المحددة للعقار. تحتفظ مارن بالحق في إلغاء الحجوزات في حالات الاحتيال أو انتهاك الشروط أو مخاوف السلامة." },
  s7: { title: "٧. السلوك المحظور", content: "يجب على المستخدمين عدم الانخراط في أنشطة احتيالية أو تقديم معلومات كاذبة أو تحريف هويتهم. يُحظر بشدة التحرش أو التمييز أو السلوك المسيء تجاه المستخدمين الآخرين. لا يجوز لك استخدام المنصة لأي أغراض غير قانونية أو لانتهاك أي قوانين. يُمنع محاولة التحايل على رسوم المنصة أو إجراء معاملات خارج المنصة. لا يُسمح بنشر قوائم مضللة أو بريد مزعج أو محتوى تجاري غير مصرح به." },
  s8: { title: "٨. التحقق وفحوصات الخلفية", content: "قد تجري مارن تحققًا من الهوية وفحوصات خلفية للمستخدمين. باستخدامك لخدماتنا، تفوضنا في الحصول على مثل هذه المعلومات. على الرغم من أننا نسعى جاهدين للتحقق من المستخدمين، إلا أن مارن لا تضمن دقة أو اكتمال معلومات التحقق وليست مسؤولة عن أي مشاكل تنشأ عن تفاعلات المستخدمين." },
  s9: { title: "٩. الملكية الفكرية", content: "جميع المحتويات على منصة مارن، بما في ذلك الشعارات والنصوص والرسومات والبرمجيات، هي ملك لمارن أو مرخصيها. لا يجوز لك نسخ محتوانا أو إعادة إنتاجه أو توزيعه أو إنشاء أعمال مشتقة منه دون إذن كتابي صريح. يظل المحتوى الذي ينشئه المستخدم (القوائم، المراجعات، الصور) ملكًا للمستخدم ولكنه يمنح مارن ترخيصًا لاستخدام هذا المحتوى لعمليات المنصة." },
  s10: { title: "١٠. حدود المسؤولية", content: "تعمل مارن كمنصة تربط أصحاب العقارات والمستأجرين وليست طرفًا في اتفاقيات الإيجار. لسنا مسؤولين عن دقة القوائم أو سلوك المستخدمين أو حالة العقارات. مارن ليست مسؤولة عن أي أضرار مباشرة أو غير مباشرة أو عرضية أو تبعية أو تأديبية تنشأ عن استخدامك للمنصة. لن تتجاوز مسؤوليتنا الإجمالية المبلغ الذي دفعته لمارن في الاثني عشر شهرًا السابقة للمطالبة." },
  s11: { title: "١١. التعويض", content: "أنت توافق على تعويض وحماية مارن والشركات التابعة لها ومسؤوليها ومديريها وموظفيها ووكلائها من أي مطالبات وأضرار وخسائر ومسؤوليات ونفقات تنشأ عن استخدامك للمنصة أو انتهاك هذه الشروط أو التعدي على حقوق أي طرف ثالث." },
  s12: { title: "١٢. حل النزاعات", content: "سيتم حل أي نزاعات تنشأ عن هذه الشروط أو استخدام المنصة من خلال التحكيم الملزم وفقًا لقواعد مركز دمياط الإقليمي للتحكيم التجاري الدولي (CRCICA). سيُعقد التحكيم في دمياط، مصر. أنت تتنازل عن حقك في المشاركة في دعاوى جماعية أو تحكيم جماعي." },
  s13: { title: "١٣. القانون الحاكم", content: "تخضع شروط الخدمة هذه لقوانين جمهورية مصر العربية، دون اعتبار لأحكام تعارض القوانين. يجب رفع أي إجراء قانوني أو دعوى قضائية حصريًا في المحاكم الموجودة في دمياط، مصر." },
  s14: { title: "١٤. معلومات الاتصال", content: "إذا كان لديك أي أسئلة حول شروط الخدمة هذه، يرجى الاتصال بنا على: البريد الإلكتروني: legal@marn.com، الهاتف: 01012345678، العنوان: بجوار جامعة دمياط الجديدة، دمياط الجديدة، مصر" }
};

const enPrivacySections = {
  s1: { title: "1. What information do we collect?", content: "We collect personal information such as your name, email address, phone number, national ID and photographs of identification documents (for legal identity verification/KYC), roommate preferences, payment details (for owners, processed securely via Stripe), chat history, and queries sent to our AI Assistant Chatbot, as well as usage data like searches, favorites, and system interactions to improve your experience." },
  s2: { title: "2. How do we protect your data?", content: "MARN uses industry-standard encryption (SSL/TLS) for data transmission. Your passwords are hashed, and we regularly audit our systems to prevent unauthorized access. Personal data is stored on secure servers, and payment details are handled entirely by Stripe, meaning we do not store your raw financial information." },
  s3: { title: "3. Do we share your information with third parties?", content: "We only share your data with property owners when you apply for a listing, or with verified service providers who help us operate (e.g., Stripe for payments, Firebase for push notifications, and Google for analytics). When you sign a contract, a SHA-256 cryptographic hash of the document is anchored to the Bitcoin blockchain using OpenTimestamps to verify its integrity. This hash contains no readable personal data. We never sell your personal information." },
  s4: { title: "4. Do we use cookies?", content: "Yes, we use cookies to remember your login status, save preferences, and analyze site traffic. You can disable cookies in your browser settings, but some features may not work properly." },
  s5: { title: "5. How can you delete your account?", content: "Go to Settings > Edit Profile > Delete Profile within the app, or email support@marn.com. Once deleted, your personal data will be removed from our active databases within 30 days, except where we are required to retain records for legal, tax, or regulatory compliance." },
  s6: { title: "6. How often is this policy updated?", content: "We update this policy whenever we change how we handle data. The 'Last Updated' date at the top will always reflect the latest version. We'll notify you via email or in-app notification for significant changes." },
  s7: { title: "7. How can you contact us about privacy?", content: "Email our Support Team at support@marn.com or write to: MARN, 123 Rental St., Suite 400, Cairo, Egypt. We respond to all privacy-related inquiries within 7 business days." },
  s8: { title: "8. Do we collect location data?", content: "With your permission, we collect your device's approximate location to show nearby properties and roommate matches. You can disable this anytime in your device settings." },
  s9: { title: "9. Do we access your camera or gallery?", content: "When you upload profile pictures, property photos, or ID documents for identity verification, we request camera/gallery access. We never access these without your action, and images are stored securely." },
  s10: { title: "10. How do we use push notifications?", content: "We send notifications for new messages, booking requests, contract status changes, payment schedules, and roommate matches. You can customize or disable these in Settings > Notifications." },
  s11: { title: "11. Do we use analytics tools?", content: "We use Google Analytics and Firebase Analytics to understand how users interact with MARN. This helps us improve features and fix bugs. All analytics data is anonymized." },
  s12: { title: "12. What are our policies for minors under 18?", content: "MARN is strictly intended for users who are 18 years of age or older. We do not knowingly collect personal data from minors under 18. If we learn that we have collected data from a minor under 18, we will take steps to delete the information and terminate the account as soon as possible." },
  s13: { title: "13. How long do we retain your data?", content: "We keep your personal data as long as your account is active. After deletion, most data is purged within 30 days. Financial and transaction records for owners and renters may be kept for up to 7 years for tax and legal compliance." },
  s14: { title: "14. What happens in case of a data breach?", content: "We have an incident response plan. If a breach affects your personal data, we will notify you within 72 hours via email and post a notice on our platform. We will also report to relevant authorities as required by law." },
  s15: { title: "15. Is this policy available in other languages?", content: "Our privacy policy is available in both English and Arabic. In the event of any discrepancies or conflict between the English and Arabic versions, the English version shall prevail and be the legally binding document." }
};

const arPrivacySections = {
  s1: { title: "١. ما هي المعلومات التي نجمعها؟", content: "نجمع معلومات شخصية مثل اسمك وعنوان بريدك الإلكتروني ورقم هاتفك والهوية الوطنية وصور وثائق الهوية (للتحقق من الهوية القانونية/اعرف عميلك) وتفضيلات رفقاء السكن وتفاصيل الدفع (للملاك، وتتم معالجتها بأمان عبر Stripe) وسجل الدردشة والاستفسارات المرسلة إلى الشات بوت المساعد بالذكاء الاصطناعي، بالإضافة إلى بيانات الاستخدام مثل عمليات البحث والمفضلات وتفاعلات النظام لتحسين تجربتك." },
  s2: { title: "٢. كيف نحمي بياناتك؟", content: "تستخدم مارن تشفيرًا متوافقًا مع معايير الصناعة (SSL/TLS) لنقل البيانات. يتم تجزئة (hash) كلمات المرور الخاصة بك، ونقوم بتدقيق أنظمتنا بانتظام لمنع الوصول غير المصرح به. يتم تخزين البيانات الشخصية على خوادم آمنة، وتتم معالجة تفاصيل الدفع بالكامل بواسطة Stripe، مما يعني أننا لا نقوم بتخزين معلوماتك المالية الخام." },
  s3: { title: "٣. هل نشارك معلوماتك مع أطراف ثالثة؟", content: "نشارك بياناتك فقط مع أصحاب العقارات عندما تتقدم بطلب لإدراج، أو مع مزودي الخدمات المعتمدين الذين يساعدوننا في العمل (مثل Stripe للمدفوعات وFirebase لإشعارات الدفع وGoogle للتحليلات). عند توقيع العقد، يتم ربط تجزئة التشفير SHA-256 للوثيقة ببلوكتشين البيتكوين باستخدام OpenTimestamps للتحقق من سلامتها. لا تحتوي هذه التجزئة على أي بيانات شخصية مقروءة. نحن لا نبيع معلوماتك الشخصية أبدًا." },
  s4: { title: "٤. هل نستخدم ملفات تعريف الارتباط؟", content: "نعم، نستخدم ملفات تعريف الارتباط لتذكر حالة تسجيل الدخول الخاصة بك، وحفظ التفضيلات، وتحليل حركة مرور الموقع. يمكنك تعطيل ملفات تعريف الارتباط في إعدادات المتصفح الخاص بك، ولكن قد لا تعمل بعض الميزات بشكل صحيح." },
  s5: { title: "٥. كيف يمكنك حذف حسابك؟", content: "انتقل إلى الإعدادات > تعديل الملف الشخصي > حذف الملف الشخصي داخل التطبيق، أو أرسل بريدًا إلكترونيًا إلى support@marn.com. بمجرد الحذف، ستتم إزالة بياناتك الشخصية من قواعد بياناتنا النشطة في غضون 30 يومًا، باستثناء الحالات التي يُطلب منا فيها الاحتفاظ بالسجلات للامتثال القانوني أو الضريبي أو التنظيمي." },
  s6: { title: "٦. كم مرة يتم تحديث هذه السياسة؟", content: "نقوم بتحديث هذه السياسة كلما قمنا بتغيير كيفية تعاملنا مع البيانات. سيعكس تاريخ 'آخر تحديث' في الأعلى دائمًا أحدث إصدار. سنقوم بإبلاغك عبر البريد الإلكتروني أو إشعار داخل التطبيق عن التغييرات المهمة." },
  s7: { title: "٧. كيف يمكنك الاتصال بنا بشأن الخصوصية؟", content: "راسل فريق الدعم عبر البريد الإلكتروني support@marn.com أو اكتب إلى: MARN, 123 Rental St., Suite 400, دمياط، مصر. نقوم بالرد على جميع الاستفسارات المتعلقة بالخصوصية في غضون 7 أيام عمل." },
  s8: { title: "٨. هل نجمع بيانات الموقع؟", content: "بإذنك، نجمع الموقع التقريبي لجهازك لإظهار العقارات القريبة وتطابقات رفقاء السكن. يمكنك تعطيل هذا في أي وقت في إعدادات جهازك." },
  s9: { title: "٩. هل نصل إلى الكاميرا أو المعرض الخاص بك؟", content: "عند تحميل صور الملف الشخصي أو صور العقار أو وثائق الهوية للتحقق من الهوية، نطلب الوصول إلى الكاميرا/المعرض. لا نصل أبدًا إلى هذه العناصر دون إجراء منك، ويتم تخزين الصور بأمان." },
  s10: { title: "١٠. كيف نستخدم إشعارات الدفع (Push Notifications)؟", content: "نرسل إشعارات بالرسائل الجديدة، وطلبات الحجز، وتغييرات حالة العقد، وجداول الدفع، وتطابقات رفقاء السكن. يمكنك تخصيص أو تعطيل هذه الإشعارات في الإعدادات > الإشعارات." },
  s11: { title: "١١. هل نستخدم أدوات التحليلات؟", content: "نستخدم Google Analytics وFirebase Analytics لفهم كيفية تفاعل المستخدمين مع مارن. يساعدنا ذلك في تحسين الميزات وإصلاح الأخطاء. يتم إخفاء هوية جميع بيانات التحليلات." },
  s12: { title: "١٢. ما هي سياساتنا للقصر دون سن 18؟", content: "تم تصميم مارن بشكل صارم للمستخدمين الذين يبلغون من العمر 18 عامًا أو أكثر. نحن لا نجمع بيانات شخصية من القصر الذين تقل أعمارهم عن 18 عامًا عن قصد. إذا علمنا أننا جمعنا بيانات من قاصر أقل من 18 عامًا، فسنتخذ خطوات لحذف المعلومات وإلغاء الحساب في أقرب وقت ممكن." },
  s13: { title: "١٣. كم من الوقت نحتفظ ببياناتك؟", content: "نحتفظ ببياناتك الشخصية طالما كان حسابك نشطًا. بعد الحذف، يتم مسح معظم البيانات في غضون 30 يومًا. قد يتم الاحتفاظ بالسجلات المالية والمعاملات للملاك والمستأجرين لمدة تصل إلى 7 سنوات للامتثال الضريبي والقانوني." },
  s14: { title: "١٤. ماذا يحدث في حالة اختراق البيانات؟", content: "لدينا خطة استجابة للحوادث. إذا أثر خرق على بياناتك الشخصية، فسنقوم بإخطارك في غضون 72 ساعة عبر البريد الإلكتروني وننشر إشعارًا على منصتنا. سنقوم أيضًا بإبلاغ السلطات ذات الصلة كما يقتضيه القانون." },
  s15: { title: "١٥. هل تتوفر هذه السياسة بلغات أخرى؟", content: "تتوفر سياسة الخصوصية الخاصة بنا باللغتين الإنجليزية والعربية. في حالة وجود أي تعارض أو تباين بين النسختين الإنجليزية والعربية، تكون النسخة الإنجليزية هي السائدة وتعتبر الوثيقة الملزمة قانونًا." }
};

enData.terms.title = "Terms of Service";
enData.terms.lastUpdated = "Last Updated: February 12, 2026";
enData.terms.intro = "Please read these terms carefully before using our platform";
enData.terms.sections = enTermsSections;

arData.terms.title = "شروط الخدمة";
arData.terms.lastUpdated = "آخر تحديث: 12 فبراير 2026";
arData.terms.intro = "يرجى قراءة هذه الشروط بعناية قبل استخدام منصتنا";
arData.terms.sections = arTermsSections;

enData.privacy.title = "MARN Privacy Policy";
enData.privacy.lastUpdated = "Last Updated: June 13, 2026";
enData.privacy.sections = enPrivacySections;

arData.privacy.title = "سياسة خصوصية مارن";
arData.privacy.lastUpdated = "آخر تحديث: 13 يونيو 2026";
arData.privacy.sections = arPrivacySections;

fs.writeFileSync(enPath, JSON.stringify(enData, null, 2));
fs.writeFileSync(arPath, JSON.stringify(arData, null, 2));

console.log('Successfully updated JSON files');
