namespace MARN_API.Enums.Property
{
    public enum City
    {
        Cairo = 0,
        Giza = 1,
        Alexandria = 2,
        NewCairo = 3,
        SixthOfOctober = 4,
        Shubra = 5,
        PortSaid = 6,
        Suez = 7,
        Luxor = 8,
        Aswan = 9,
        Mansoura = 10,
        Tanta = 11,
        Ismailia = 12,
        Faiyum = 13,
        Zagazig = 14,
        Damietta = 15,
        Asyut = 16,
        Minya = 17,
        BeniSuef = 18,
        Sohag = 19,
        Hurghada = 20,
        SharmElSheikh = 21,
        Obour = 22,
        Helwan = 23,
        Nasr = 24,
        Maadi = 25,
        Heliopolis = 26,
        Dokki = 27,
        Mohandessin = 28,
        NewAdministrativeCapital = 29,
        ElShorouk = 30,
        BorgElArab = 31,
        Badr = 32,
        TenthOfRamadan = 33,
        Rehab = 34,
        Tagamoa = 35,
        Sadat = 36,
        Benha = 37,
        KafrElSheikh = 38,
        Qena = 39,
        MarsaAlam = 40
    }
}
